### ISSUE TITLE
Usability: Distractor marker faaaaaaaaaaaaaar away from the correct radio button

### ISSUE THREAD

**Issue by mudrd8mz** [ethz-let/moodle-qtype_sc#2]
I was looking for how the heck I am supposed to mark distractors, went back to the question settings multiple times etc - only to find out the cross on the opposite side of the screen than the correct marker / widget is present.

![image](https://user-images.githubusercontent.com/85831/76624414-8ce96700-6535-11ea-9ce6-6a742544a38a.png)

I think this might be an usability issue. Did you consider (if possible) to make it so that it is more intuitive for the user to guess what to do with this question type?

**Comment by Clyxz** [comment]
Hi David,
 
thank you for your feedback!
 
I understand your point and we also took that into consideration a while ago when we were working on the specifications for this question type. The reason why we decided against it was a combination of following aspects:
 
- In running quizzes there is less screenspace: the quiz navigation is included, also there might be other blocks next to the main content. 

- the option-text usually has more content than just three letters: Therefore in a running quiz, the distractor icon is not too far away from the text of the option as linked in your preview example. 
 
From an usability reason we considered placing the distractor icon on a different place, not next to the option-radio would have two advantages:
- the student will not click onto the distractor-checkbox by mistake. 
- also option-radios and distractor-checkboxes which clearly have a different functionality are separated by space which underlines their different purpose.
 
Please note, we are aware that there is no real right or wrong in this matter. We totally get your point and were also having debates about that issue before but decided to go with the current setup because of the user feedback so far and because of the points mentioned above.
 
I apologize for the late response, we currently have a huge workload regarding the situation with COVID-19 which results in changes on our working-progress.

**Comment by mudrd8mz** [comment]
Ok. Thank you for having thought about it.
